export default defineEventHandler(async (event) => {
  const query = getQuery(event);
  const version = query.version as string;

  try {
    // Fetch the statically generated update.json from the root
    // This file is generated by GitHub Actions and committed to the repo, 
    // then served by Nuxt at the root.
    const updateData = await $fetch<any>('https://tumult.jackg.cc/update.json');

    // Validation: If it's not JSON (e.g. HTML fallback), return 204
    if (!updateData || typeof updateData !== 'object' || !updateData.version) {
       console.warn("[Updater] Invalid update metadata received:", updateData);
       setResponseStatus(event, 204);
       return;
    }

    // If version matches, return 204 No Content as per Tauri spec
    if (updateData.version === version) {
       setResponseStatus(event, 204);
       return;
    }

    return updateData;

  } catch (e) {
    console.error("Failed to fetch update info:", e);
    throw createError({
      statusCode: 500,
      statusMessage: "Failed to fetch update info"
    });
  }
});
