name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Enable Corepack
        run: corepack enable
        shell: bash

      - name: Set Yarn Version
        run: |
          corepack yarn set version stable
          corepack yarn -v
        shell: bash

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          # Matrix key ensures Windows doesn't try to use Mac's compiled binaries
          key: ${{ matrix.platform }}

      - name: Install dependencies
        run: corepack yarn
        shell: bash

      - name: Set version from tag
        shell: bash
        run: |
          VERSION="${{ github.ref_name }}"
          node -e "
            const fs = require('fs');
            const path = 'src-tauri/tauri.conf.json';
            const config = JSON.parse(fs.readFileSync(path, 'utf8'));
            config.version = '${VERSION}'; 
            fs.writeFileSync(path, JSON.stringify(config, null, 2));
          "

      - name: Build and Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "App Release ${{ github.ref_name }}"
          releaseBody: "Automated Windows and MacOS build."
          releaseDraft: true
          prerelease: true
          tauriScript: corepack yarn tauri
          projectPath: .
          args: --verbose
